apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiZ2hjci5pbyI6IHsiYXV0aCI6ICJZMlY0T21kb2NGOTNkR1J2UTNwaFVVUnpka1ZtU2xONFNXMTJaMjVFY0RKaU1reG9kREEwWlU1elIyST0ifX0=
type: kubernetes.io/dockerconfigjson
