apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJRM0poZW5sRmJHVndhR0Z1ZEZnNloyaHdYemxqZW1WemNWUm9RVWRNZURSWU1rc3pWRWcyV1hWd1JXdDRabHBxY2pCbVlXdG5Odz09In19fQ==
type: kubernetes.io/dockerconfigjson
